// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/c-bata/go-prompt"
)

var Ps = []prompt.Suggest{
	prompt.Suggest{Text: "-a", Description: "Show all containers (default shows just running)"},
	prompt.Suggest{Text: "--all", Description: "Show all containers (default shows just running)"},
	prompt.Suggest{Text: "-n", Description: "Show n last created containers (includes all states) (default -1)"},
	prompt.Suggest{Text: "--last int", Description: "Show n last created containers (includes all states) (default -1)"},
	prompt.Suggest{Text: "-l", Description: "Show the latest created container (includes all states)"},
	prompt.Suggest{Text: "--latest", Description: "Show the latest created container (includes all states)"},
	prompt.Suggest{Text: "--no-trunc", Description: "Don't truncate output"},
	prompt.Suggest{Text: "-q", Description: "Only display numeric IDs"},
	prompt.Suggest{Text: "--quiet", Description: "Only display numeric IDs"},
	prompt.Suggest{Text: "-s", Description: "Display total file sizes"},
	prompt.Suggest{Text: "--size", Description: "Display total file sizes"},
}
