// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Builder = []prompt.Suggest{
	prompt.Suggest{Text: "build", Description: "Build an image from a Dockerfile"},
	prompt.Suggest{Text: "prune", Description: "Remove build cache"},
}
