// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Rmi = []prompt.Suggest{
	prompt.Suggest{Text: "-f", Description: "Force removal of the image"},
	prompt.Suggest{Text: "--force", Description: "Force removal of the image"},
}
