// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/c-bata/go-prompt"
)

var Search = []prompt.Suggest{
	prompt.Suggest{Text: "--limit int", Description: "Max number of search results (default 25)"},
	prompt.Suggest{Text: "--no-trunc", Description: "Don't truncate output"},
}
