// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Trust = []prompt.Suggest{
	prompt.Suggest{Text: "inspect", Description: "Return low-level information about keys and signatures"},
	prompt.Suggest{Text: "revoke", Description: "Remove trust for an image"},
	prompt.Suggest{Text: "sign", Description: "Sign an image"},
}
