// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Attatch = []prompt.Suggest{
	prompt.Suggest{Text: "--config string", Description: "Location of client config files (default \"/Users/denizcakan/.docker\")"},
	prompt.Suggest{Text: "-c", Description: "Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with \"docker context use\")"},
	prompt.Suggest{Text: "--context string", Description: "Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with \"docker context use\")"},
	prompt.Suggest{Text: "-D", Description: "Enable debug mode"},
	prompt.Suggest{Text: "--debug", Description: "Enable debug mode"},
	prompt.Suggest{Text: "-H", Description: "Daemon socket(s) to connect to"},
	prompt.Suggest{Text: "--host list", Description: "Daemon socket(s) to connect to"},
	prompt.Suggest{Text: "--tls", Description: "Use TLS; implied by --tlsverify"},
	prompt.Suggest{Text: "--tlscert string", Description: "Path to TLS certificate file (default \"/Users/denizcakan/.docker/cert.pem\")"},
	prompt.Suggest{Text: "--tlskey string", Description: "Path to TLS key file (default \"/Users/denizcakan/.docker/key.pem\")"},
	prompt.Suggest{Text: "--tlsverify", Description: "Use TLS and verify the remote"},
	prompt.Suggest{Text: "-v", Description: "Print version information and quit"},
	prompt.Suggest{Text: "--version", Description: "Print version information and quit"},
}
