// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Version = []prompt.Suggest{
	prompt.Suggest{Text: "-f", Description: "Format the output using the given Go template"},
	prompt.Suggest{Text: "--format string", Description: "Format the output using the given Go template"},
}
