// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/c-bata/go-prompt"
)

var Import = []prompt.Suggest{
	prompt.Suggest{Text: "-c", Description: "Apply Dockerfile instruction to the created image"},
	prompt.Suggest{Text: "--change list", Description: "Apply Dockerfile instruction to the created image"},
}
