// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Update = []prompt.Suggest{
	prompt.Suggest{Text: "--blkio-weight uint16", Description: "Block IO (relative weight), between 10 and 1000, or 0 to disable (default 0)"},
	prompt.Suggest{Text: "--cpu-period int", Description: "Limit CPU CFS (Completely Fair Scheduler) period"},
	prompt.Suggest{Text: "--cpu-quota int", Description: "Limit CPU CFS (Completely Fair Scheduler) quota"},
	prompt.Suggest{Text: "--cpu-rt-period int", Description: "Limit the CPU real-time period in microseconds"},
	prompt.Suggest{Text: "--cpu-rt-runtime int", Description: "Limit the CPU real-time runtime in microseconds"},
	prompt.Suggest{Text: "-c", Description: "CPU shares (relative weight)"},
	prompt.Suggest{Text: "--cpu-shares int", Description: "CPU shares (relative weight)"},
	prompt.Suggest{Text: "--cpus decimal", Description: "Number of CPUs"},
	prompt.Suggest{Text: "--cpuset-cpus string", Description: "CPUs in which to allow execution (0-3, 0,1)"},
	prompt.Suggest{Text: "--cpuset-mems string", Description: "MEMs in which to allow execution (0-3, 0,1)"},
	prompt.Suggest{Text: "--kernel-memory bytes", Description: "Kernel memory limit"},
	prompt.Suggest{Text: "-m", Description: "Memory limit"},
	prompt.Suggest{Text: "--memory bytes", Description: "Memory limit"},
	prompt.Suggest{Text: "--memory-swap bytes", Description: "Swap limit equal to memory plus swap: '-1' to enable unlimited swap"},
	prompt.Suggest{Text: "--pids-limit int", Description: "Tune container pids limit (set -1 for unlimited)"},
	prompt.Suggest{Text: "--restart string", Description: "Restart policy to apply when a container exits"},
}
