// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Plugin = []prompt.Suggest{
	prompt.Suggest{Text: "create", Description: "Create a plugin from a rootfs and configuration. Plugin data directory must contain config.json and rootfs directory."},
	prompt.Suggest{Text: "disable", Description: "Disable a plugin"},
	prompt.Suggest{Text: "enable", Description: "Enable a plugin"},
	prompt.Suggest{Text: "inspect", Description: "Display detailed information on one or more plugins"},
	prompt.Suggest{Text: "install", Description: "Install a plugin"},
	prompt.Suggest{Text: "ls", Description: "List plugins"},
	prompt.Suggest{Text: "push", Description: "Push a plugin to a registry"},
	prompt.Suggest{Text: "rm", Description: "Remove one or more plugins"},
	prompt.Suggest{Text: "set", Description: "Change settings for a plugin"},
	prompt.Suggest{Text: "upgrade", Description: "Upgrade an existing plugin"},
}
