// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Start = []prompt.Suggest{
	prompt.Suggest{Text: "-a", Description: "Attach STDOUT/STDERR and forward signals"},
	prompt.Suggest{Text: "--attach", Description: "Attach STDOUT/STDERR and forward signals"},
	prompt.Suggest{Text: "-i", Description: "Attach container's STDIN"},
	prompt.Suggest{Text: "--interactive", Description: "Attach container's STDIN"},
}
