// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Stats = []prompt.Suggest{
	prompt.Suggest{Text: "-a", Description: "Show all containers (default shows just running)"},
	prompt.Suggest{Text: "--all", Description: "Show all containers (default shows just running)"},
	prompt.Suggest{Text: "--no-stream", Description: "Disable streaming stats and only pull the first result"},
	prompt.Suggest{Text: "--no-trunc", Description: "Do not truncate output"},
}
