// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Cp = []prompt.Suggest{
	prompt.Suggest{Text: "-a", Description: "Archive mode (copy all uid/gid information)"},
	prompt.Suggest{Text: "--archive", Description: "Archive mode (copy all uid/gid information)"},
}
