// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/c-bata/go-prompt"
)

var Network = []prompt.Suggest{
	prompt.Suggest{Text: "connect", Description: "Connect a container to a network"},
	prompt.Suggest{Text: "create", Description: "Create a network"},
	prompt.Suggest{Text: "inspect", Description: "Display detailed information on one or more networks"},
	prompt.Suggest{Text: "ls", Description: "List networks"},
	prompt.Suggest{Text: "prune", Description: "Remove all unused networks"},
	prompt.Suggest{Text: "rm", Description: "Remove one or more networks"},
}
