// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/c-bata/go-prompt"
)

var Service = []prompt.Suggest{
	prompt.Suggest{Text: "create", Description: "Create a new service"},
	prompt.Suggest{Text: "inspect", Description: "Display detailed information on one or more services"},
	prompt.Suggest{Text: "logs", Description: "Fetch the logs of a service or task"},
	prompt.Suggest{Text: "ls", Description: "List services"},
	prompt.Suggest{Text: "ps", Description: "List the tasks of one or more services"},
	prompt.Suggest{Text: "rm", Description: "Remove one or more services"},
	prompt.Suggest{Text: "rollback", Description: "Revert changes to a service's configuration"},
	prompt.Suggest{Text: "scale", Description: "Scale one or multiple replicated services"},
	prompt.Suggest{Text: "update", Description: "Update a service"},
}
