// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/c-bata/go-prompt"
)

var Load = []prompt.Suggest{
	prompt.Suggest{Text: "-q", Description: "Suppress the load output"},
	prompt.Suggest{Text: "--quiet", Description: "Suppress the load output"},
}
