// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Config = []prompt.Suggest{
	prompt.Suggest{Text: "create", Description: "Create a config from a file or STDIN"},
	prompt.Suggest{Text: "inspect", Description: "Display detailed information on one or more configs"},
	prompt.Suggest{Text: "ls", Description: "List configs"},
	prompt.Suggest{Text: "rm", Description: "Remove one or more configs"},
}
