// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Container = []prompt.Suggest{
	prompt.Suggest{Text: "attach", Description: "Attach local standard input, output, and error streams to a running container"},
	prompt.Suggest{Text: "commit", Description: "Create a new image from a container's changes"},
	prompt.Suggest{Text: "cp", Description: "Copy files/folders between a container and the local filesystem"},
	prompt.Suggest{Text: "create", Description: "Create a new container"},
	prompt.Suggest{Text: "diff", Description: "Inspect changes to files or directories on a container's filesystem"},
	prompt.Suggest{Text: "exec", Description: "Run a command in a running container"},
	prompt.Suggest{Text: "export", Description: "Export a container's filesystem as a tar archive"},
	prompt.Suggest{Text: "inspect", Description: "Display detailed information on one or more containers"},
	prompt.Suggest{Text: "kill", Description: "Kill one or more running containers"},
	prompt.Suggest{Text: "logs", Description: "Fetch the logs of a container"},
	prompt.Suggest{Text: "ls", Description: "List containers"},
	prompt.Suggest{Text: "pause", Description: "Pause all processes within one or more containers"},
	prompt.Suggest{Text: "port", Description: "List port mappings or a specific mapping for the container"},
	prompt.Suggest{Text: "prune", Description: "Remove all stopped containers"},
	prompt.Suggest{Text: "rename", Description: "Rename a container"},
	prompt.Suggest{Text: "restart", Description: "Restart one or more containers"},
	prompt.Suggest{Text: "rm", Description: "Remove one or more containers"},
	prompt.Suggest{Text: "run", Description: "Run a command in a new container"},
	prompt.Suggest{Text: "start", Description: "Start one or more stopped containers"},
	prompt.Suggest{Text: "stats", Description: "Display a live stream of container(s) resource usage statistics"},
	prompt.Suggest{Text: "stop", Description: "Stop one or more running containers"},
	prompt.Suggest{Text: "top", Description: "Display the running processes of a container"},
	prompt.Suggest{Text: "unpause", Description: "Unpause all processes within one or more containers"},
	prompt.Suggest{Text: "update", Description: "Update configuration of one or more containers"},
	prompt.Suggest{Text: "wait", Description: "Block until one or more containers stop, then print their exit codes"},
}
