// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Secret = []prompt.Suggest{
	prompt.Suggest{Text: "create", Description: "Create a secret from a file or STDIN as content"},
	prompt.Suggest{Text: "inspect", Description: "Display detailed information on one or more secrets"},
	prompt.Suggest{Text: "ls", Description: "List secrets"},
	prompt.Suggest{Text: "rm", Description: "Remove one or more secrets"},
}
