// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Inspect = []prompt.Suggest{
	prompt.Suggest{Text: "-s", Description: "Display total file sizes if the type is container"},
	prompt.Suggest{Text: "--size", Description: "Display total file sizes if the type is container"},
	prompt.Suggest{Text: "--type string", Description: "Return JSON for specified type"},
}
