// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Logs = []prompt.Suggest{
	prompt.Suggest{Text: "--details", Description: "Show extra details provided to logs"},
	prompt.Suggest{Text: "-f", Description: "Follow log output"},
	prompt.Suggest{Text: "--follow", Description: "Follow log output"},
	prompt.Suggest{Text: "--tail string", Description: "Number of lines to show from the end of the logs (default \"all\")"},
	prompt.Suggest{Text: "-t", Description: "Show timestamps"},
	prompt.Suggest{Text: "--timestamps", Description: "Show timestamps"},
}
