// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/c-bata/go-prompt"
)

var Rm = []prompt.Suggest{
	prompt.Suggest{Text: "-f", Description: "Force the removal of a running container (uses SIGKILL)"},
	prompt.Suggest{Text: "--force", Description: "Force the removal of a running container (uses SIGKILL)"},
	prompt.Suggest{Text: "-l", Description: "Remove the specified link"},
	prompt.Suggest{Text: "--link", Description: "Remove the specified link"},
}
