// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/c-bata/go-prompt"
)

var Commit = []prompt.Suggest{
	prompt.Suggest{Text: "-a", Description: "Author (e.g., \"John Hannibal Smith <hannibal@a-team.com>\")"},
	prompt.Suggest{Text: "--author string", Description: "Author (e.g., \"John Hannibal Smith <hannibal@a-team.com>\")"},
	prompt.Suggest{Text: "-c", Description: "Apply Dockerfile instruction to the created image"},
	prompt.Suggest{Text: "--change list", Description: "Apply Dockerfile instruction to the created image"},
	prompt.Suggest{Text: "-p", Description: "Pause container during commit (default true)"},
	prompt.Suggest{Text: "--pause", Description: "Pause container during commit (default true)"},
}
