// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/c-bata/go-prompt"
)

var System = []prompt.Suggest{
	prompt.Suggest{Text: "df", Description: "Show docker disk usage"},
	prompt.Suggest{Text: "events", Description: "Get real time events from the server"},
	prompt.Suggest{Text: "info", Description: "Display system-wide information"},
	prompt.Suggest{Text: "prune", Description: "Remove unused data"},
}
