// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Pull = []prompt.Suggest{
	prompt.Suggest{Text: "-a", Description: "Download all tagged images in the repository"},
	prompt.Suggest{Text: "--all-tags", Description: "Download all tagged images in the repository"},
	prompt.Suggest{Text: "-q", Description: "Suppress verbose output"},
	prompt.Suggest{Text: "--quiet", Description: "Suppress verbose output"},
}
