// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Login = []prompt.Suggest{
	prompt.Suggest{Text: "--password-stdin", Description: "Take the password from stdin"},
}
