// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var Image = []prompt.Suggest{
	prompt.Suggest{Text: "build", Description: "Build an image from a Dockerfile"},
	prompt.Suggest{Text: "history", Description: "Show the history of an image"},
	prompt.Suggest{Text: "import", Description: "Import the contents from a tarball to create a filesystem image"},
	prompt.Suggest{Text: "inspect", Description: "Display detailed information on one or more images"},
	prompt.Suggest{Text: "load", Description: "Load an image from a tar archive or STDIN"},
	prompt.Suggest{Text: "ls", Description: "List images"},
	prompt.Suggest{Text: "prune", Description: "Remove unused images"},
	prompt.Suggest{Text: "pull", Description: "Pull an image or a repository from a registry"},
	prompt.Suggest{Text: "push", Description: "Push an image or a repository to a registry"},
	prompt.Suggest{Text: "rm", Description: "Remove one or more images"},
	prompt.Suggest{Text: "save", Description: "Save one or more images to a tar archive (streamed to STDOUT by default)"},
	prompt.Suggest{Text: "tag", Description: "Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE"},
}
