// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/c-bata/go-prompt"
)

var Node = []prompt.Suggest{
	prompt.Suggest{Text: "demote", Description: "Demote one or more nodes from manager in the swarm"},
	prompt.Suggest{Text: "inspect", Description: "Display detailed information on one or more nodes"},
	prompt.Suggest{Text: "ls", Description: "List nodes in the swarm"},
	prompt.Suggest{Text: "promote", Description: "Promote one or more nodes to manager in the swarm"},
	prompt.Suggest{Text: "ps", Description: "List tasks running on one or more nodes, defaults to current node"},
	prompt.Suggest{Text: "rm", Description: "Remove one or more nodes from the swarm"},
	prompt.Suggest{Text: "update", Description: "Update a node"},
}
