// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/c-bata/go-prompt"
)

var Swarm = []prompt.Suggest{
	prompt.Suggest{Text: "ca", Description: "Display and rotate the root CA"},
	prompt.Suggest{Text: "init", Description: "Initialize a swarm"},
	prompt.Suggest{Text: "join", Description: "Join a swarm as a node and/or manager"},
	prompt.Suggest{Text: "leave", Description: "Leave the swarm"},
	prompt.Suggest{Text: "unlock", Description: "Unlock swarm"},
	prompt.Suggest{Text: "update", Description: "Update the swarm"},
}
