// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/c-bata/go-prompt"
)

var Context = []prompt.Suggest{
	prompt.Suggest{Text: "create", Description: "Create a context"},
	prompt.Suggest{Text: "export", Description: "Export a context to a tar or kubeconfig file"},
	prompt.Suggest{Text: "import", Description: "Import a context from a tar or zip file"},
	prompt.Suggest{Text: "inspect", Description: "Display detailed information on one or more contexts"},
	prompt.Suggest{Text: "ls", Description: "List contexts"},
	prompt.Suggest{Text: "rm", Description: "Remove one or more contexts"},
	prompt.Suggest{Text: "update", Description: "Update a context"},
	prompt.Suggest{Text: "use", Description: "Set the current docker context"},
}
