// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/c-bata/go-prompt"
)

var Images = []prompt.Suggest{
	prompt.Suggest{Text: "-a", Description: "Show all images (default hides intermediate images)"},
	prompt.Suggest{Text: "--all", Description: "Show all images (default hides intermediate images)"},
	prompt.Suggest{Text: "--digests", Description: "Show digests"},
	prompt.Suggest{Text: "--no-trunc", Description: "Don't truncate output"},
	prompt.Suggest{Text: "-q", Description: "Only show numeric IDs"},
	prompt.Suggest{Text: "--quiet", Description: "Only show numeric IDs"},
}
