// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/gohumble/go-prompt"
)

var History = []prompt.Suggest{
	prompt.Suggest{Text: "-H", Description: "Print sizes and dates in human readable format (default true)"},
	prompt.Suggest{Text: "--human", Description: "Print sizes and dates in human readable format (default true)"},
	prompt.Suggest{Text: "--no-trunc", Description: "Don't truncate output"},
	prompt.Suggest{Text: "-q", Description: "Only show numeric IDs"},
	prompt.Suggest{Text: "--quiet", Description: "Only show numeric IDs"},
}
