// Code generated by 'option-gen'. DO NOT EDIT.

package options

import (
	prompt "github.com/c-bata/go-prompt"
)

var Volume = []prompt.Suggest{
	prompt.Suggest{Text: "create", Description: "Create a volume"},
	prompt.Suggest{Text: "inspect", Description: "Display detailed information on one or more volumes"},
	prompt.Suggest{Text: "ls", Description: "List volumes"},
	prompt.Suggest{Text: "prune", Description: "Remove all unused local volumes"},
	prompt.Suggest{Text: "rm", Description: "Remove one or more volumes"},
}
